services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: controle-familiar-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "ControleFin@2026!"
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
